" Execute pathogen
execute pathogen#infect()

set nocompatible                  " Must come first because it changes other options.

let mapleader=','		              " Map leader.

syntax enable                     " Turn on syntax highlighting.
filetype plugin indent on         " Turn on file type detection.

runtime macros/matchit.vim        " Load the matchit plugin.

set showcmd                       " Display incomplete commands.
set showmode                      " Display the mode you're in.

set backspace=indent,eol,start    " Intuitive backspacing.

set hidden                        " Handle multiple buffers better.

set wildmenu                      " Enhanced command line completion.
set wildmode=list:longest         " Complete files like a shell.

set ignorecase                    " Case-insensitive searching.
set smartcase                     " But case-sensitive if expression contains a capital letter.

set number                        " Show line numbers.
set ruler                         " Show cursor position.

set incsearch                     " Highlight matches as you type.
set hlsearch                      " Highlight matches.

set wrap                          " Turn on line wrapping.
set scrolloff=3                   " Show 3 lines of context around the cursor.

set title                         " Set the terminal's title

set visualbell                    " No beeping.

set nobackup                      " Don't make a backup before overwriting a file.
set nowritebackup                 " And again.
set directory=$HOME/.vim/tmp//,.  " Keep swap files in one location

set tabstop=2                     " Global tab width.
set shiftwidth=2                  " And again, related.
set expandtab                     " Use spaces instead of tabs

set laststatus=2                  " Show the status line all the time

" Useful status information at bottom of screen
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P

colorscheme vividchalk

" Tab mappings.
map <leader>tt :tabnew<cr>
map <leader>te :tabedit
map <leader>tc :tabclose<cr>
map <leader>to :tabonly<cr>
map <leader>tn :tabnext<cr>
map <leader>tp :tabprevious<cr>
map <leader>tf :tabfirst<cr>
map <leader>tl :tablast<cr>
map <leader>tm :tabmove

" Unmap arrow keys.
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

" Silver searcher
let g:ag_prg="/usr/local/bin/ag --column"

" Set the tag file search order
set tags=./tags
set tags+=gems.tags

" Map F5 to re-index ctags
nnoremap <f5> :!ctags -R<CR>

" Set comment char for Ruby
autocmd FileType ruby set commentstring=#\ %s

" Set spell checking for markdown and asciidoc
autocmd BufRead,BufNewFile *.md setlocal spell
autocmd BufRead,BufNewFile *.adoc setlocal spell
" Set word completion
set complete+=kspell

" Open NERDTree when vim starts up
" autocmd vimenter * NERDTree

" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

" Map RuboCop
nmap <Leader>r :RuboCop<CR>

" Automatically execute ctags each time a file is saved
" :autocmd BufWritePost * call system("ctags -R")

" Automatic fold settings for specific files. Uncomment to use.
" autocmd FileType ruby setlocal foldmethod=syntax
" autocmd FileType css  setlocal foldmethod=indent shiftwidth=2 tabstop=2

autocmd Filetype gitcommit setlocal spell textwidth=72

hi Search cterm=NONE ctermfg=grey ctermbg=blue
